### ISSUE TITLE
vocab file

### ISSUE THREAD

**Issue by hash2430** [enlipleai/kor_pratrain_LM#3]
vocab file도 upload해주실수 있나요??

**Comment by jeonsworld** [comment]
안녕하세요. vocab file은 [Large-V1 Download (330M Params)](https://drive.google.com/file/d/1n0B3pK8DkkBvEpEXnjUX4a523LfPtumx/view?usp=sharing)를 통해 다운받아 압축을 해제하면 포함되어 있습니다. 감사합니다~
