### ISSUE TITLE
Pretrain시 사용한 코드도 공개해주실 수 있나요?

### ISSUE THREAD

**Issue by hwijeen** [enlipleai/kor_pratrain_LM#4]
Pretrain시 두 가지 masking strategy와 additional task를 사용하셨다고 README에 적어주셨는데,
정확한 파악을 위해서 pretrain시 사용한 코드도 공개해주실 수 있나요?
감사합니다.

**Comment by jeonsworld** [comment]
n-gram masking 및 SOP 관련 소스는 다음을 참고해주시기 바랍니다.
[n-gram masking](https://github.com/zihangdai/xlnet/blob/bbaa3a6fa0b3a2ee694e8cf66167434f9eca9660/data_utils.py#L331)  
[SOP](https://github.com/google-research/albert/blob/c21d8a3616a4b156d21e795698ad52743ccd8b73/create_pretraining_data.py#L343)
