### ISSUE TITLE
LM pretrain 코드도 공개해주실 수 있나요?

### ISSUE THREAD

**Issue by hash2430** [enlipleai/kor_pratrain_LM#6]
공개하신 코드에서 down-stream task 훈련에 사용된 Processor 구조는 single thread에 ram위에 list를 올리는 접근이니, 확장해서 pretrain 을 구현하기에는 시간과 메모리 스케일이 너무 커서 제약이 있어보이네요.. 별도의 방법으로 pretrain을 하셨을 것 같은데, 해당 코드는 올려주신 것에 포함이 안 되어 있는 것 같아서요,, 공개해 주실 수 있나요??

**Comment by hash2430** [comment]
아마 해당 코드는 업로드가 곤란하셔서 안하신거겠쬬.. 무리한 부탁은 하고 싶지 않아요..실례했네용

**Comment by jeonsworld** [comment]
안녕하세요. pretrain step에서 corpus의 크기에 따라 메모리에 모두 로딩이 어려워 여러개의 파일로 분할하여 진행하였습니다.
